<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="121" started-at="2022-03-08T22:03:00 IST" finished-at="2022-03-08T22:03:00 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="121" started-at="2022-03-08T22:03:00 IST" finished-at="2022-03-08T22:03:00 IST">
      <class name="testng.DependsOnMethods">
        <test-method status="PASS" signature="initilization()[pri:0, instance:testng.DependsOnMethods@1f554b06]" name="initilization" is-config="true" duration-ms="7" started-at="2022-03-08T22:03:00 IST" finished-at="2022-03-08T22:03:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilization -->
        <test-method status="FAIL" signature="validateloginTest()[pri:1, instance:testng.DependsOnMethods@1f554b06]" name="validateloginTest" duration-ms="12" started-at="2022-03-08T22:03:00 IST" finished-at="2022-03-08T22:03:00 IST">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at testng.DependsOnMethods.validateloginTest(DependsOnMethods.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateloginTest -->
        <test-method status="PASS" signature="closeResources()[pri:0, instance:testng.DependsOnMethods@1f554b06]" name="closeResources" is-config="true" duration-ms="1" started-at="2022-03-08T22:03:00 IST" finished-at="2022-03-08T22:03:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeResources -->
        <test-method status="SKIP" signature="validateProductSearch()[pri:2, instance:testng.DependsOnMethods@1f554b06]" name="validateProductSearch" duration-ms="0" started-at="2022-03-08T22:03:00 IST" depends-on-methods="testng.DependsOnMethods.validateloginTest" finished-at="2022-03-08T22:03:00 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependsOnMethods.validateProductSearch()[pri:2, instance:testng.DependsOnMethods@1f554b06] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependsOnMethods.validateProductSearch()[pri:2, instance:testng.DependsOnMethods@1f554b06] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateProductSearch -->
      </class> <!-- testng.DependsOnMethods -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
